Add Angular template
tauri-apps/create-tauri-app pull request #167
Opened 2022-09-09 21:44 UTC by eneajaho

### What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/create-tauri-app/blob/dev/.changes/readme.md).
- [ ] I have added a convincing reason for adding this feature, if necessary

### Other information

2022-09-10 10:37 UTC, amrbashir requested changes
Thank you for this awesome PR, and sorry for the delay

2022-09-10 10:37 UTC, amrbashir commented on packages/cli/fragments/_assets_/angular.svg
> +<?xml version="1.0" encoding="utf-8"?>
this file already exists in the fragment, no need to keep it here

2022-09-10 10:37 UTC, amrbashir commented on packages/cli/fragments/fragment-angular/_cta_manifest_
> +angular.svg = src/assets/angular.svg
```suggestion
```

2022-09-10 10:37 UTC, amrbashir commented on packages/cli/fragments/fragment-angular/src/assets/tauri.svg
> +<svg width="206" height="231" viewBox="0 0 206 231" fill="none" xmlns="http://www.w3.org/2000/svg">
remove this file since it will be copied over from `_assets_`. Also remove `.gitkeep` file, it serves no purpose.

2022-09-10 10:37 UTC, amrbashir commented on packages/cli/fragments/fragment-angular/src/styles.scss
> +/* You can add global styles to this file, and also import other style files */
remove this file, it will be copied over from `base/src/styles`

2022-09-10 10:37 UTC, amrbashir commented on packages/cli/fragments/fragment-angular/src/typings.d.ts
> +    __TAURI__: any;
no need to add this typings file since the tempaltes uses `@tauri-apps/api`

2022-09-10 10:37 UTC, amrbashir commented
don't worry about `next-ts` and `next` failing in CI tests, I will take care of that.

2022-09-10 15:01 UTC, eneajaho commented
Hi @amrbashir 
I pushed the changes you requested!

2022-09-10 17:09 UTC, amrbashir requested changes
final changes before I merge. don't forget to run `pnpm i` then `pnpm format` in the repo root.

2022-09-10 17:09 UTC, amrbashir commented on packages/cli/fragments/fragment-angular/_cta_manifest_
> +devPath = http://localhost:4200
```suggestion
devPath = http://localhost:1420
```

2022-09-10 17:09 UTC, amrbashir commented on packages/cli/fragments/fragment-angular/package.json
> +      "dev": "ng serve",
```suggestion
      "dev": "ng serve --port 1420",
```

2022-09-10 17:09 UTC, amrbashir commented on packages/cli/fragments/fragment-angular/angular.json
> +  "newProjectRoot": "projects",
```suggestion
  "newProjectRoot": "projects",
  "cli": {
  	"analytics": false
  },
```

2022-09-10 17:09 UTC, amrbashir commented on packages/cli/fragments/fragment-angular/src/app/app.component.ts
> +          <input #nameInput placeholder="Enter a name..." />
```suggestion
          <input #greet-input placeholder="Enter a name..." />
```

2022-09-10 18:59 UTC, eneajaho commented
@amrbashir All done.

2022-09-11 13:29 UTC, ProfeJulianLasso commented
Sorry, so was it possible to support Angular in order to create apps with this framework? Thank you.

2022-09-11 18:27 UTC, amrbashir approved these changes
Thank you

2022-09-11 18:27 UTC, merged