fix: handle SIGINT on user prompt, closes (#509)
tauri-apps/create-tauri-app pull request #511
Opened 2023-10-28 22:58 UTC by Mulling

### What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [x] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [ ] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/create-tauri-app/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### Other information

In reference to #509, this PR adds a SIGINT handler using the `ctrlc` crate (though I'm not 100% sold on this crate, it seems to be de-facto way to handle SIGINT on Rust programs). Some of the logic of the prompts is also changed as to not die on `unwrap`.

Since dialoguer seems to be only hiding the cursor, and not changing the termios state, I think for now we only need to re-enable the cursor.

2023-10-28 23:47 UTC, amrbashir requested changes

2023-10-28 23:47 UTC, amrbashir commented on packages/cli/src/main.rs
> +    ctrlc::set_handler(move || eprint!("\x1b[?25h")).expect("fail to set SIGINT handler");
This should probably be moved into the `run` method in `lib.rs` so it can affect the JS CLI as well.

2023-10-28 23:47 UTC, amrbashir commented on packages/cli/src/lib.rs
> +                defaults.project_name.context("project_name not defined")?
```suggestion
                defaults.project_name.context("default project_name not set")?
```

2023-10-28 23:47 UTC, amrbashir commented on packages/cli/src/lib.rs
> +                defaults.manager.context("manager not set")?
```suggestion
                defaults.manager.context("default manager not set")?
```

2023-10-28 23:47 UTC, amrbashir commented on packages/cli/src/lib.rs
> +                let category = category.context("category not set")?;
```suggestion
                let category = category.context("category shouldn't be None at this point")?;
```

2023-10-28 23:47 UTC, amrbashir commented on packages/cli/src/lib.rs
> +                defaults.template.context("template not set")?
```suggestion
                defaults.template.context("default template not set")?
```

2023-10-28 23:47 UTC, amrbashir commented on packages/cli/src/lib.rs
> +                defaults.mobile.unwrap()
```suggestion
                defaults.mobile.context("default mobile not set")?
```

2023-10-28 23:47 UTC, amrbashir commented
Thank you for your contribution, this is a really good refactor.

2023-10-29 13:35 UTC, Mulling commented
Hey, Thanks. I've made the changes you requested.

2023-10-30 12:31 UTC, amrbashir approved these changes, later dismissed

2023-10-30 12:31 UTC, amrbashir commented
Thank you

2023-10-30 12:59 UTC, Mulling commented
Do you want me to downgrade `ctrl` to 3.4.0? It doesn't have a rustc minimum requirement like version 3.4.1. Sorry for that, didn´t see it :grin:

2023-10-30 13:12 UTC, amrbashir commented
I think `3.4.0` also needs 1.59 on Linux, so I'd appreciate if we can downgrade it to a version that meets 1.59 rust requirment.

2023-10-30 13:45 UTC, Mulling commented
Ok, I've downgraded `ctrlc` to 3.3.1, tested on stable-x86_64-unknown-linux-gnu and 1.59.0-x86_64-unknown-linux-gnu, seems good now.

2023-10-30 13:48 UTC, amrbashir commented on packages/cli/Cargo.toml
> +ctrlc = "=3.3.1"
```suggestion
ctrlc = "3.3"
```

2023-10-30 14:25 UTC, amrbashir approved these changes

2023-10-30 14:25 UTC, merged