Fix false warning deno missing dependencies #830
tauri-apps/create-tauri-app pull request #831
Opened 2024-10-26 18:34 UTC by PawsFunctions

Set `skip` to true in case Deno or Bun is the package manager. The existence of the package will be checked separately, and a notice for missing dependencies will still be provided when Cargo is used to create a project with Deno or Bun as the package manager.

2024-10-26 18:48 UTC, PawsFunctions commented
It will cover cases and fix notices for Rust, Bun, and Node.js.

**I don't have Deno or Node.js, so the notices are accurate.**

#### cargo + Deno
```
cargo run 001                                                                                                                              create-tauri-app/git/dev !
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/cargo-create-tauri-app 001`
✔ Package name · tauri-app
✔ Identifier · com.tauri-app.app
✔ 001 directory is not empty, do you want to overwrite? · yes
✔ Choose which language to use for your frontend · TypeScript / JavaScript - (pnpm, yarn, npm, deno, bun)
✔ Choose your package manager · deno
✔ Choose your UI template · Vue - (https://vuejs.org/)
✔ Choose your UI flavor · TypeScript

Template created!

Your system is missing dependencies (or they do not exist in $PATH):
╭──────┬──────────────────────────╮
│ Deno │ Visit https://deno.land/ │
╰──────┴──────────────────────────╯
...
```
#### cargo + Bun
```
cargo run 001                                                                                                                              create-tauri-app/git/dev !
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/cargo-create-tauri-app 001`
✔ Package name · tauri-app
✔ Identifier · com.tauri-app.app
✔ 001 directory is not empty, do you want to overwrite? · yes
✔ Choose which language to use for your frontend · TypeScript / JavaScript - (pnpm, yarn, npm, deno, bun)
✔ Choose your package manager · bun
✔ Choose your UI template · Vanilla
✔ Choose your UI flavor · TypeScript

Template created! To get started run:
  cd 001
....
```


## No effect on existing solutions

#### cargo + nodejs (npm | Pnpm | Yarn )
```
❯ cargo run 001                                                                                                                              create-tauri-app/git/dev !
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/cargo-create-tauri-app 001`
✔ Package name · tauri-app
✔ Identifier · com.tauri-app.app
✔ 001 directory is not empty, do you want to overwrite? · yes
✔ Choose which language to use for your frontend · TypeScript / JavaScript - (pnpm, yarn, npm, deno, bun)
✔ Choose your package manager · npm
✔ Choose your UI template · Vue - (https://vuejs.org/)
✔ Choose your UI flavor · TypeScript

Template created!

Your system is missing dependencies (or they do not exist in $PATH):
╭─────────┬───────────────────────────╮
│ Node.js │ Visit https://nodejs.org/ │
╰─────────┴───────────────────────────╯
...
```

#### Cargo + Rust frontend

```
 cargo run 001                                                                                                                              create-tauri-app/git/dev !
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/cargo-create-tauri-app 001`
✔ Package name · tauri-app
✔ Identifier · com.tauri-app.app
✔ 001 directory is not empty, do you want to overwrite? · yes
✔ Choose which language to use for your frontend · Rust - (cargo)
✔ Choose your UI template · Yew - (https://yew.rs/)

Template created! To get started run:
  cd 001
....
```

2024-10-27 08:40 UTC, amrbashir requested changes
Could you please add a change file in `.changes` directory?

2024-10-27 16:32 UTC, PawsFunctions commented
Sorry, I just added it now. I hope I did it the right way.

2024-10-27 16:33 UTC, amrbashir commented on .changes/bug_deno-bun_missing.md
> +Fix: Removed false warning about missing dependencies deno and bun.
```suggestion
Fixed false warning about missing dependencies, Deno and Bun.
```

2024-10-27 16:33 UTC, amrbashir approved these changes
Thank you

2024-10-27 16:34 UTC, merged